with-expecter: true
packages:
  github.com/d-strobel/gowindows/connection:
    config:
      all: true
      dir: ./connection/mocks
  github.com/d-strobel/gowindows/parser:
    config:
      all: true
      dir: ./parser/mocks
